-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "MealType" ADD VALUE 'QUICK_BITES';
ALTER TYPE "MealType" ADD VALUE 'FINGER_FOODS';
ALTER TYPE "MealType" ADD VALUE 'BAKED_GOODS';
ALTER TYPE "MealType" ADD VALUE 'FROZEN_TREATS';
ALTER TYPE "MealType" ADD VALUE 'HOLIDAY_SWEETS';
ALTER TYPE "MealType" ADD VALUE 'SMOOTHIES';
ALTER TYPE "MealType" ADD VALUE 'COCKTAILS';
ALTER TYPE "MealType" ADD VALUE 'HOT_BEVERAGES';
ALTER TYPE "MealType" ADD VALUE 'FRESH_JUICES';
ALTER TYPE "MealType" ADD VALUE 'MEAL_PREP';
ALTER TYPE "MealType" ADD VALUE 'BATCH_COOKING';
ALTER TYPE "MealType" ADD VALUE 'FREEZER_MEALS';
ALTER TYPE "MealType" ADD VALUE 'LUNCHBOX_MEALS';
ALTER TYPE "MealType" ADD VALUE 'PARTY_FOOD';
ALTER TYPE "MealType" ADD VALUE 'HOLIDAY_MEALS';
ALTER TYPE "MealType" ADD VALUE 'CELEBRATION_CAKES';
ALTER TYPE "MealType" ADD VALUE 'PICNIC_FOOD';
ALTER TYPE "MealType" ADD VALUE 'BBQ_GRILLING';
ALTER TYPE "MealType" ADD VALUE 'POST_WORKOUT';
ALTER TYPE "MealType" ADD VALUE 'DETOX_MEALS';
ALTER TYPE "MealType" ADD VALUE 'COMFORT_FOOD';
ALTER TYPE "MealType" ADD VALUE 'ENERGY_BOOSTERS';
ALTER TYPE "MealType" ADD VALUE 'STREET_FOOD';
ALTER TYPE "MealType" ADD VALUE 'TAPAS_SMALL_PLATES';
ALTER TYPE "MealType" ADD VALUE 'FAMILY_STYLE';
ALTER TYPE "MealType" ADD VALUE 'BUFFET_STYLE';
ALTER TYPE "MealType" ADD VALUE 'KETO_MEALS';
ALTER TYPE "MealType" ADD VALUE 'VEGAN_MEALS';
ALTER TYPE "MealType" ADD VALUE 'GLUTEN_FREE';
ALTER TYPE "MealType" ADD VALUE 'LOW_CARB';
ALTER TYPE "MealType" ADD VALUE 'HIGH_PROTEIN';
ALTER TYPE "MealType" ADD VALUE 'ONE_POT_MEALS';
ALTER TYPE "MealType" ADD VALUE 'NO_COOK_MEALS';
ALTER TYPE "MealType" ADD VALUE 'SLOW_COOKER';
ALTER TYPE "MealType" ADD VALUE 'AIR_FRYER';
ALTER TYPE "MealType" ADD VALUE 'GRILLED_MEALS';
